//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoWinformsBTL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Loans = new HashSet<Loan>();
        }
    
        public int BookID { get; set; }
        public string Title { get; set; }
        public Nullable<int> AuthorID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> Edition { get; set; }
        public Nullable<int> Year { get; set; }
        public string Genre { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loan> Loans { get; set; }
    }
}
